name: BSDs
on: push

jobs:
  build_bsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y \
            bash \
            boost-libs \
            cmake git \
            llvm18 \
            ninja \
            qt6-base qt6-declarative qt6-shadertools qt6-websockets qt6-serialport qt6-scxml \
            ffmpeg \
            lilv suil lv2 \
            libcoap \
            portaudio \
            pd \
            libfmt spdlog \
            rubberband libsamplerate libsndfile \
            libcoap \
            freetype2 harfbuzz fontconfig \
            alsa-lib jackit

        run: |
          ./ci/common.deps.sh
          ./ci/freebsd.build.sh
