name: Debian build
on: [push,pull_request]

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    container:
      image: debian:${{ matrix.distro }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { distro: bookworm, CC: clang-19,  CXX: clang++-19, PACKAGES: "clang-19" }
          - { distro: bookworm, CC: gcc,       CXX: g++,        PACKAGES: "build-essential" }
          - { distro: trixie, CC: gcc,      CXX: g++,     PACKAGES: "build-essential gcc-14 g++-14 llvm-17-dev libclang-17-dev " }
          - { distro: trixie, CC: clang-19,    CXX: clang++-19, PACKAGES: "build-essential clang-19 llvm-19-dev libclang-19-dev " }
    steps:
      - name: Install git
        run: |
          apt-get update -qq
          apt-get install -qq --force-yes git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
          PACKAGES: ${{ matrix.packages }}
        run: |
          ./ci/${{ matrix.distro }}.deps.sh

      - name: Build
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
        run: |
          ./ci/${{ matrix.distro }}.build.sh
