name: macOS build

on: push

jobs:
  brew:
    name: macOS (Release, Brew, Intel)
    runs-on: macos-13
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Dependencies
        run: |
          ./ci/osx-brew.deps.sh

      - name: Build
        run: |
          ./ci/osx-brew.build.sh

  brew-m1:
    name: macOS (Release, Brew, AppleSilicon)
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/osx-brew.deps.sh

      - name: Build
        run: |
          ./ci/osx-brew.build.sh

  brew-m1-dev:
    name: macOS (Dev, Brew, AppleSilicon)
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/osx-brew.deps.sh

      - name: Build
        run: |
          ./ci/developer.build.sh -S "$PWD" -B build-developer

  m1-test:
    name: macOS (Test CMake)
    runs-on: macos-14
    steps:
      - run: |
          echo 'int main() { }' > main.cpp
          printf 'cmake_minimum_required(VERSION 3.25)\nproject(foo)\nmessage("CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")\nmessage("CMAKE_HOST_SYSTEM_PROCESSOR: ${CMAKE_HOST_SYSTEM_PROCESSOR}")\nadd_executable(foo main.cpp)' > CMakeLists.txt
         
          echo " ======== 1 ======== "
          cmake -S . -B build1

          export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH

          if [[ -d /Applications/Xcode_15.4.app ]]; then
            export XCODE_ROOT=/Applications/Xcode_15.4.app
            sudo xcode-select -s "$XCODE_ROOT"
          elif [[ -d /Applications/Xcode_15.3.app ]]; then
            export XCODE_ROOT=/Applications/Xcode_15.3.app
            sudo xcode-select -s "$XCODE_ROOT"
          elif [[ -d /Applications/Xcode_15.2.app ]]; then
            export XCODE_ROOT=/Applications/Xcode_15.2.app
            sudo xcode-select -s "$XCODE_ROOT"
          elif [[ -d /Applications/Xcode_15.1.app ]]; then
            export XCODE_ROOT=/Applications/Xcode_15.1.app
            sudo xcode-select -s "$XCODE_ROOT"
          elif [[ -d /Applications/Xcode_15.0.app ]]; then
            export XCODE_ROOT=/Applications/Xcode_15.0.app
            sudo xcode-select -s "$XCODE_ROOT"
          else
            export XCODE_ROOT=/Applications/Xcode.app
          fi

          echo " ======== 2 ======== "
          cmake -S . -B build2


  m1-package:
    name: macOS (AppleSilicon Release)
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - run: |
          source ci/osx-package.deps.sh
        env:
          MACOS_ARCH: "aarch64"
          MAC_CERT_B64: ${{ secrets.MAC_CERT_B64 }}
          MAC_CODESIGN_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}

      - run: |
          source ci/osx-package.build.sh
        env:
          MACOS_ARCH: "aarch64"

      - run: |
          export GITTAGNOV=$(echo "$GITHUB_REF" | sed "s/.*\///;s/^v//")
          export BUILD_ARTIFACTSTAGINGDIRECTORY=$PWD/staging
          mkdir $BUILD_ARTIFACTSTAGINGDIRECTORY
          source ci/osx-package.deploy.sh
        env:
          MACOS_ARCH: "aarch64"
          MAC_ALTOOL_PASSWORD: ${{ secrets.MAC_ALTOOL_PASSWORD }}

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: macos-aarch64
          path: |
            staging/*.*