name: macOS build

on: push

jobs:
  brew:
    name: macOS (Brew)
    runs-on: macos-12
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/osx-brew.deps.sh

      - name: Build
        run: |
          ./ci/osx-brew.build.sh