name: Ubuntu build

on: push

jobs:
  jammy:
    name: Ubuntu 
    runs-on: linux-selfhosted

    strategy:
      matrix:
        include:
          - { deploy: true , distro: jammy, CC: gcc-12,    CXX: g++-12,     LDFLAGS: "" }
          - { deploy: false, distro: jammy, CC: clang-14,  CXX: clang++-14, LDFLAGS: "-fuse-ld=lld" }
          - { deploy: true,  distro: lunar, CC: gcc,       CXX: g++,     LDFLAGS: "-fuse-ld=lld" }
          - { deploy: false, distro: lunar, CC: clang,     CXX: clang++, LDFLAGS: "-fuse-ld=lld" }

    container:
      image: ubuntu:${{ matrix.distro }}
      
    steps:
      - name: Install git
        run: |
          apt-get update -qq
          apt-get install -qq --force-yes git

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/${{ matrix.distro }}.deps.sh

      - name: Build
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
          LDFLAGS: ${{ matrix.LDFLAGS }}
        run: |
          ./ci/${{ matrix.distro }}.build.sh

      - name: Deploy
        run: |
          ./ci/${{ matrix.distro }}.deploy.sh

      - name: Upload build
        uses: actions/upload-artifact@v2
        if: matrix.deploy 
        with:
          name: ${{ matrix.distro }}-amd64
          path: |
            *.deb
